version: "3"
services:
  app:
    container_name: rosetta-sol-go
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RPC_URL=${RPC_URL}
      - PORT=8080
      - NETWORK=${NETWORK:-TESTNET}
      - MODE=${MODE}
